server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bitespeed
    username: root2
    password: root2

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
    show-sql: true